# Change these first
owner: spectaA # Your GitHub organization or username, where this repository lives
repo: uptime-test # The name of this repository

sites:
  - name: prod-pzt.mokapis.com
    url: https://prod-pzt.mokapis.com/api/info

  - name: stag-pzt.mokapis.com
    url: https://stag-pzt.mokapis.com/api/info

  - name: www.pizzattitude.com
    url: https://www.pizzattitude.com

  - name: admin.pizzattitude.com
    url: https://admin.pizzattitude.com

  - name: stag-mwd.mokapis.com
    url: https://stag-mwd.mokapis.com/api/info

  - name: prod-mwd.mokapis.com
    url: https://prod-mwd.mokapis.com/api/info

  - name: www.marionwillems.be
    url: https://www.marionwillems.be/

assignees:
  - spectaA
  - Taewenn
  - gowiea

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime-test
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime for OrangeBleu
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Issue page for OrangeBleu clients, API and websites
  navbar:
    - title: GitHub
      href: https://github.com/spectaA/uptime-test
    - title: Issues
      href: https://github.com/spectaA/uptime-test/issues

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
